name: Build PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v22

    - name: Install devenv
      uses: cachix/cachix-action@v12
      with:
        name: devenv

    - name: Install dependencies
      run: nix-shell --run "devenv shell" < /dev/null

    - name: Build PDF
      run: |
        nix-shell --run "devenv shell" <<EOF
        just build
        EOF

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: resume.pdf