name: Build PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
    - name: Build PDF
      shell: devenv shell bash -- -e {0}
      run: |
        just compile

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: resume.pdf

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: resume.pdf
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          Automated release v${{ github.run_number }}

          Commit: ${{ github.sha }}
          [View the full commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}