name: Build PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
    - name: Build PDF
      shell: devenv shell bash -- -e {0}
      run: |
        just compile

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: resume.pdf